#ifndef SETUP_H_
#define SETUP_H_

//#define BIG_ENDIAN
#define PERVERTION
#define FUNCTION_IGNORE_GLOBAL_ERRORS

//#define DEBUG_MODE
//#define DEBUG_MALLOC

#define CONSOLE_CMD_DELIMITERCHARSTR "~"
#define CONSOLE_LINE_MAXLENGTH 80
#define CONSOLE_STRING_VALUE_MAX_LEN (64)

#ifdef PERVERTION
#define MAXBONUSTABLEVALUE 20
#else
#define MAXBONUSTABLEVALUE 30
#endif



#endif /* SETUP_H_ */
