
#if (!defined ENODESENUMS_H_) || (defined XENUM_IMPLEMENT_MODE)
#ifndef XENUM_IMPLEMENT_MODE
#define ENODESENUMS_H_
#endif

#include "enums.h"

XENUM_BEGIN(DataTypes)
XENUM_LINE(eDTVoid, "VOID", 0)
XENUM_LINE(eDTCollection, "COLLECTION", 1)
XENUM_LINE(eDTReference, "REFERENCE", 2)
XENUM_LINE(eDTReferedID, "REFEREDID", 3)
XENUM_LINE(eDTPtrUser, "REF_USER", 4)
XENUM_LINE(eDTPtrU8, "REF_BYTE", 5)
XENUM_LINE(eDTPtrS8, "REF_CHAR", 6)
XENUM_LINE(eDTPtrU16, "REF_WORD", 7)
XENUM_LINE(eDTPtrS16, "REF_SHORT", 8)
XENUM_LINE(eDTPtrU32, "REF_DWORD", 9)
XENUM_LINE(eDTPtrS32, "REF_INT", 10)
XENUM_LINE(eDTString, "REF_STRING", 11)
XENUM_LINE(eDTReserved0, "RESERVED0", 12)
XENUM_LINE(eDTReserved1, "RESERVED1", 13)
XENUM_LINE(eDTReserved2, "RESERVED2", 14)
XENUM_LINE(eDTReserved3, "RESERVED3", 15)
XENUM_LINE(eDTDataU8, "BYTE", 16)
XENUM_LINE(eDTDataS8, "CHAR", 17)
XENUM_LINE(eDTDataU16, "WORD", 18)
XENUM_LINE(eDTDataS16, "SHORT", 19)
XENUM_LINE(eDTDataU32, "DWORD", 20)
XENUM_LINE(eDTDataS32, "INT", 21)
XENUM_LINE(eDTsIPv4, "S_IPV4", 22)
XENUM_LINE(eDTsCharacter, "S_CHAR", 23)
XENUM_LINE(eDTsMemFile, "S_MEMF", 24)
XENUM_LINE(eDTCOUNT, "COUNTER", 25)
XENUM_END(DataTypes)

#endif /* ENODESENUMS_H_ */
