
#define LOADED_ENUM_NAMEX eDataTypes
#define LOADED_ENUM_NAMES strDataTypes
#define LOADED_ENUM_NAMET \
	LOADED_ENUM_VALUE(eDTNone,"NOVALUE")\
	LOADED_ENUM_VALUE(eDTCollection,"COLLECTION")\
	LOADED_ENUM_VALUE(eDTReference,"REFERENCE")\
	LOADED_ENUM_VALUE(eDTReferedID,"REFEREDID")\
	LOADED_ENUM_VALUE(eDTPtrUser,"REF_USER")\
	LOADED_ENUM_VALUE(eDTPtrU8,"REF_BYTE")\
	LOADED_ENUM_VALUE(eDTPtrS8,"REF_CHAR")\
	LOADED_ENUM_VALUE(eDTPtrU16,"REF_WORD")\
	LOADED_ENUM_VALUE(eDTPtrS16,"REF_SHORT")\
	LOADED_ENUM_VALUE(eDTPtrU32,"REF_DWORD")\
	LOADED_ENUM_VALUE(eDTPtrS32,"REF_INT")\
	LOADED_ENUM_VALUE(eDTString,"REF_STRING")\
	LOADED_ENUM_VALUE(eDTReserved0,"RESERVED0")\
	LOADED_ENUM_VALUE(eDTReserved1,"RESERVED1")\
	LOADED_ENUM_VALUE(eDTReserved2,"RESERVED2")\
	LOADED_ENUM_VALUE(eDTReserved3,"RESERVED3")\
	LOADED_ENUM_VALUE(eDTDataU8,"DAT_BYTE")\
	LOADED_ENUM_VALUE(eDTDataS8,"DAT_CHAR")\
	LOADED_ENUM_VALUE(eDTDataU16,"DAT_WORD")\
	LOADED_ENUM_VALUE(eDTDataS16,"DAT_SHORT")\
	LOADED_ENUM_VALUE(eDTDataU32,"DAT_DWORD")\
	LOADED_ENUM_VALUE(eDTDataS32,"DAT_INT")\
	LOADED_ENUM_VALUE(eDTsMemFile,"REF_S_MEMFILE")\
	LOADED_ENUM_VALUE(eDTsCharacter,"REF_S_CHAR")\
	LOADED_ENUM_VALUE(eDTCOUNT,"COUNTER")

#include "enums.inc.h"
